import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layouts/Footer";
import Navbar from "../components/layouts/Navbar";
import MuiProvider from "@/provider/MuiProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link rel="preload" href="https://localhost:3000" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <MuiProvider>
          <Navbar />
          {children}
          <Footer />
        </MuiProvider>
      </body>
    </html>
  );
}
